services:
  - type: web
    name: msg-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server/server.py
    envVars:
      - key: MSG_DB
        value: /tmp/msg_server.db
